services:
  - type: web
    name: bfhl-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
